apiVersion: v1
kind: Template
metadata:
  name: openshift-activemq
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: openshift-activemq
    name: openshift-activemq
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: openshift-activemq
      deploymentconfig: openshift-activemq
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: openshift-activemq
          deploymentconfig: openshift-activemq
      spec:
        containers:
        - image: ''
          imagePullPolicy: Always
          name: openshift-activemq
          ports:
          - containerPort: 61616
            protocol: TCP
          - containerPort: 8161
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - openshift-activemq
        from:
          kind: ImageStreamTag
          name: openshift-activemq:latest
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: openshift-activemq
    name: openshift-activemq
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: openshift-activemq:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/natronq/openshift-activemq.git
      type: Git
    strategy:
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: iC5AZ9ft5C5XgfrYkKQT
      type: GitHub
    - generic:
        secret: -z44GI1g-dXhvhWSGc5W
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: openshift-activemq
    name: openshift-activemq
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: openshift-activemq
    name: openshift-activemq
  spec:
    ports:
    - name: 8161-tcp
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: 61616-tcp
      port: 61616
      protocol: TCP
      targetPort: 61616
    selector:
      app: openshift-activemq
      deploymentconfig: openshift-activemq
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: openshift-activemq
    name: activemq
  spec:
    port:
      targetPort: 8161-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: openshift-activemq
      weight: 100
    wildcardPolicy: None
